name: Build Go

on:
  workflow_dispatch:
    inputs:
      tool_name:
        description: 'Tên thư mục (Ví dụ: _template)'
        required: true
        type: string

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./go-tools

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable' # Luôn lấy bản mới nhất
          cache-dependency-path: go-tools/${{ inputs.tool_name }}/go.sum

      - name: Build (Optimized)
        shell: pwsh
        run: |
          cd ${{ inputs.tool_name }}

          if (Test-Path "go.sum") {
            go mod download
          } else {
            go mod tidy
          }

          New-Item -ItemType Directory -Force -Path "../../dist" | Out-Null

          # SỬA DÒNG NÀY: Thêm ./src vào cuối lệnh build
          # Go sẽ tìm file main.go trong folder src
          go build -ldflags "-s -w" -o "../../dist/${{ inputs.tool_name }}.exe" ./src

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.tool_name }}_go
          path: dist/*.exe
          if-no-files-found: error
